### ISSUE TITLE
lost "volumeClaimTemplates>metadata>name "'s value after apply yaml,  this issue cause recreate pvc  when redeploy.

### ISSUE THREAD

**Issue by feiyuyitiao** [apache/rocketmq-operator#117]
after deploy, view k8s sts  broker-0-master or broker-0-replica-1, it miss  " volumeClaimTemplates (name: namesrv-storage" or "storageClassName: rocketmq-storage") which defined in template file rocketmq_v1alpha1_rocketmq_cluster.yaml. from bellow snapshot, operator generator a new name.  this issue cause recreate pvc when redeploy.
![image](https://user-images.githubusercontent.com/5387559/180177141-99abdc1c-23d5-474a-b2df-e0c3aa7ad4a1.png)

**temp fix by:**
pkg/controller/nameservice/nameservice_controller.go:257 , method: getVolumeClaimTemplates()
......
		templates := nameService.Spec.VolumeClaimTemplates 
		templates[0].ObjectMeta.Name = "namesrv-storage" 
		return templates
.......
pkg/controller/broker/broker_controller.go:507 , method: getVolumeClaimTemplates()
.....
		templates := broker.Spec.VolumeClaimTemplates 
		templates[0].ObjectMeta.Name = "broker-storage" 
		return templates
.....

**Comment by feiyuyitiao** [comment]
I found the 'https://github.com/apache/rocketmq-operator/pull/116' fixed yesterday.
so I add change " crd:generateEmbeddedObjectMeta=true "  in manifests: controller-gen, fix currentissue. thanks!

sorry, I dont' familar with operatorframework.

**Comment by caigy** [comment]
Solved by #116

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Likely Valid**

This is a known class of issues with Kubernetes operators where `volumeClaimTemplates` metadata (name, storageClassName) gets stripped during reconciliation. The operator likely overwrites the StatefulSet spec without preserving the VCT sub-fields.

**Root cause hypothesis:** The operator's reconciliation logic reconstructs the StatefulSet object and loses the `volumeClaimTemplates.metadata.name` and `storageClassName` fields, causing PVC recreation on redeploy.

**Note:** Filed July 2022. Please verify against the current operator version — this may have been addressed in later releases.

---
*Automated evaluation by RockteMQ-AI*
