### ISSUE TITLE
Event resource permission is missing

### ISSUE THREAD

**Issue by gobbq** [apache/rocketmq-operator#119]
Event resource permission is missing, operator logs as follows:

![image](https://user-images.githubusercontent.com/9428795/181510645-4a14e8e6-2f3b-489a-a4dc-7c78d1850a82.png)

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Likely Valid**

This appears to be a RBAC configuration issue where the operator's ClusterRole is missing permissions for Event resources. The controller needs `events` API group access to record Kubernetes events during reconciliation.

**Note:** This issue was filed in July 2022. The operator codebase may have evolved since then — please verify against the current `develop` branch to confirm if the RBAC rules have been updated.

---
*Automated evaluation by RockteMQ-AI*
