### ISSUE TITLE
Operator will update nameservers addr always.

### ISSUE THREAD

**Issue by shangjin92** [apache/rocketmq-operator#120]
Sometimes, hostsIps are equal to instance.Status.NameServers, just the order of value is different. But reflect.DeepEqual will return false to this situation, so operator will update nameservices always.

For example, hostIps = ['192.168.2.1', '192.168.2.11'], instance.Status.NameServers = ['192.168.2.11', '192.168.2.1']

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Confirmed**

The operator unnecessarily updates the NameServer StatefulSet on every reconciliation loop because `reflect.DeepEqual` compares string slices by element order, while Kubernetes may return the list in a different order than what is defined in the CRD.

**Root Cause:** In the reconciliation logic, the operator compares the desired NameServer list with the current StatefulSet's command args. Even when the content is identical, `reflect.DeepEqual` returns false if the ordering differs, triggering an unnecessary update.

**Impact:** Continuous unnecessary updates to the NameServer StatefulSet, which can cause brief disruptions and noisy reconciliation logs.

**Fix:** Sort both slices before comparison, or use a set-based comparison (e.g., `cmp.Diff` with `cmpopts.SortSlices`).

**Note:** This issue has been open since Dec 2022 and marked stale. The fix is straightforward and would be a good first contribution.

---
*Automated evaluation by github-manager*
