### ISSUE TITLE
make deploy error

### ISSUE THREAD

**Issue by HoHenSer** [apache/rocketmq-operator#150]
![image](https://user-images.githubusercontent.com/8278941/216531705-e8314484-805b-40a9-9c53-34119984a501.png)

**Comment by caigy** [comment]
Pls run `go mod tidy` first. You may refer to #148.

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Needs Info**

This issue reports a `make deploy` error but only includes a screenshot without a text description of the error message, environment, or steps to reproduce.

**To proceed with investigation, please provide:**
- [ ] The exact error message (as text, not just a screenshot)
- [ ] Your environment (OS, Go version, Kubernetes version, operator branch/tag)
- [ ] Steps to reproduce

**Note:** This issue was opened in February 2023 (~3 years ago). If the issue is no longer relevant, maintainers may close it.

---
*Automated evaluation by github-manager*
