### ISSUE TITLE
My app that outside the k8s's cluster  can't interview the rockermq that be dployed in k8s

### ISSUE THREAD

**Issue by yhz1985** [apache/rocketmq-operator#62]
I deploy the nameserver's service for Nodeport，but My app that outside the k8s's cluster  can't interview the rockermq that be dployed in k8s.
And I look at the logs ,it tell me the app interview  the broker pod's ip。 Why it is?

 
![image](https://user-images.githubusercontent.com/19431363/94357603-e2015a80-00cc-11eb-8af3-d454d292861e.png)

**Comment by linjiemiao** [comment]
This is because the ip of the broker is the intranet ip of k8s, and the ip registered by the broker with the nameserver is also the intranet ip. Therefore, you cannot directly access the intranet ip of the broker outside the cluster. If your development environment needs to be debugged, you can use docker-compose to deploy a cluster. Then you can use rocketmq-operator to deploy in the test environment and production environment.


rocketmq-docker-compose: https://github.com/silotrd/rocketmq-docker-compose
