### ISSUE TITLE
the nameservice in master and slave

### ISSUE THREAD

**Issue by carloscao0928** [apache/rocketmq-operator#76]
![微信截图_20210621164022](https://user-images.githubusercontent.com/58930323/122733382-b43df080-d2af-11eb-8955-f5d4cdee1515.png)

the name address in master can be correctly,but in slave is empty,whats wrong,

**Comment by waney316** [comment]
do you hava fix and resolve the problem ? i met it  when i deploy the rocketmq  cluster，one of the broker nameserver address maybe empty

**Comment by caigy** [comment]
1. Could you provide the log of operator at that time?
2. Did this problem occur in your initial deployment, or after scaling?

**Comment by caigy** [comment]
It may be caused by empty PodIP in the following procedure:
https://github.com/apache/rocketmq-operator/blob/aabcbe4bef9ad09f1c7009c1cf91511f9a514a36/pkg/controller/nameservice/nameservice_controller.go#L282-L288

@carloscao0928 @waney316 Could you provide more about your Kubernetes version, network type and CNI plugin?
[](https://github.com/kubernetes/kubernetes/issues/43531)

**Comment by waney316** [comment]
k8s version is 1.21.7，
CNI plugin: flannel v0.15.1
the cluster build by rancher
@caigy

**Comment by caigy** [comment]
@waney316 @carloscao0928 pls find if #94 can solve the problem.
