### ISSUE TITLE
replica can not restart automatically

### ISSUE THREAD

**Issue by overstep123** [apache/rocketmq-operator#80]
The issue tracker is **ONLY** used for the bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before you raise a new one.

I use example/rocketmq_v1alpha1_rocketmq_cluster.yaml to startup a rocketMQ cluster. But the replica pod can not restart automatically. The error in the broker.log is 
![image](https://user-images.githubusercontent.com/41141842/130381108-e45c91ef-e3f4-4a2f-9ad0-eb8723612943.png)

. The subscriptionGroup.json and subscriptionGroup.json.bak are both have the same content "<nil>". And I found that is because the replica pod execute the command 'echo "<nil>" > subscriptionGroup.json'. 
![image](https://user-images.githubusercontent.com/41141842/130381538-f4f4a544-fde1-41d6-b73f-98507b340713.png)

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
    Use the operator to startup a rocketMQ cluster(the size is 2),and kill one replica pod.
 
- What did you expect to see?
    The replica pod is restarting again and again.

- What did you see instead?
    The replica pod can startup successfully

2. Please tell us about your environment:
     operator version: the latest master branch.
     kubernetes version: v1.19.10

**Comment by caigy** [comment]
The problem can be reproduced by following steps:
1. Start a RocketMQ cluster with 2 brokers;
2. When no subscription exists, that is, the file `/root/store/config/subscriptionGroup.json` in broker-0-master-0 does NOT exists, increase the size of cluster;
3. The added brokers will failed to start because  `/root/store/config/subscriptionGroup.json` contains `<nil>`, which is an invalid JSON string.

Cause：
When the actual size of cluster is less than the specified number, the broker controller will create new brokers, and copy `subscriptionGroup.json` in broker-0-master-0 to the added brokers. However, if that file does not exists, `controller/broker.exec` just returns a string "<nil>", which is copied to the added brokers.

**Comment by caigy** [comment]
@overstep123 Would you submit a PR to fix it?
